### ISSUE TITLE
Play audio node

### ISSUE THREAD

**Issue by drewlahart** [samuelvogelmann/VisualTJ#1]
Hi Samuel,
Thanks for creating this flow. I've been using it but had trouble with the audio out. The "Output audio" node in the _Audio Output result class with Text to Speech_ section of the flow doesn't seem to be reading the audio out. 

So, I switched the node to a "Play Audio" purple output node and disconnected the red "Output audio" node. Then the audio worked great. 
Thanks

**Comment by samuelvogelmann** [comment]
Hi Drew,

first of all sorry for the late response and thanks for reporting your problem.

So, I tested both options ("exec"-node with aplay, "play audio"-node with a buffer of a wav file) on a "naked" Raspberry Pi with the latest Raspbian and both worked. 

Maybe there is a configuration problem within your "alsa mixer" on your Pi and that's why the `aplay` command is not working. To test the alsa mixer try `test speaker` or `aplay /usr/share/scratch/Media/Sounds/Vocals/Singer2.wav` to play some test sounds. Let me know if it worked!

But as your solution works perfectly, there is no need for you to switch back to the exec-node with aplay. 

Thanks
